# Generated by Django 5.0.1 on 2025-07-29 19:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import shared.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[shared.validators.validate_field])),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='EncounterSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[shared.validators.validate_field])),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Source',
            },
        ),
        migrations.CreateModel(
            name='MultiModalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_view', models.BooleanField(default=False, verbose_name='Provider View')),
                ('patient_view', models.BooleanField(default=False, verbose_name='Patient View')),
                ('room_view', models.BooleanField(default=False, verbose_name='Room View')),
                ('audio', models.BooleanField(default=False, verbose_name='Audio')),
                ('transcript', models.BooleanField(default=False, verbose_name='Transcript')),
                ('patient_survey', models.BooleanField(default=False, verbose_name='Patient Survey')),
                ('provider_survey', models.BooleanField(default=False, verbose_name='Provider Survey')),
                ('patient_annotation', models.BooleanField(default=False, verbose_name='Patient Annotation')),
                ('provider_annotation', models.BooleanField(default=False, verbose_name='Provider Annotation')),
                ('rias_transcript', models.BooleanField(default=False, verbose_name='RIAS Transcript')),
                ('rias_codes', models.BooleanField(default=False, verbose_name='RIAS Codes')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Multi Modal Data Path',
                'verbose_name_plural': 'Multi Modal Data Paths',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.PositiveIntegerField(unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, validators=[shared.validators.validate_field])),
                ('last_name', models.CharField(blank=True, max_length=255, validators=[shared.validators.validate_field])),
                ('date_of_birth', models.DateField(blank=True, null=True, validators=[shared.validators.validate_time])),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown')], max_length=5)),
                ('race', models.CharField(blank=True, choices=[('AI', 'American Indian or Alaska Native'), ('AS', 'Asian'), ('BA', 'Black or African American'), ('NH', 'Native Hawaiian or Other Pacific Islander'), ('WH', 'White'), ('MR', 'Multiple Race'), ('OT', 'Other'), ('UN', 'Unknown')], max_length=5)),
                ('ethnicity', models.CharField(blank=True, choices=[('H', 'Hispanic or Latino'), ('NH', 'Not Hispanic or Latino'), ('U', 'Unknown')], max_length=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.PositiveIntegerField(unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, validators=[shared.validators.validate_field])),
                ('last_name', models.CharField(blank=True, max_length=255, validators=[shared.validators.validate_field])),
                ('date_of_birth', models.DateField(blank=True, null=True, validators=[shared.validators.validate_time])),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown')], max_length=5)),
                ('race', models.CharField(blank=True, choices=[('AI', 'American Indian or Alaska Native'), ('AS', 'Asian'), ('BA', 'Black or African American'), ('NH', 'Native Hawaiian or Other Pacific Islander'), ('WH', 'White'), ('MR', 'Multiple Race'), ('OT', 'Other'), ('UN', 'Unknown')], max_length=5)),
                ('ethnicity', models.CharField(blank=True, choices=[('H', 'Hispanic or Latino'), ('NH', 'Not Hispanic or Latino'), ('U', 'Unknown')], max_length=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csn_number', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[shared.validators.validate_numeric], verbose_name='CSN Number')),
                ('case_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Case ID')),
                ('encounter_date_and_time', models.DateTimeField(default=django.utils.timezone.now, validators=[shared.validators.validate_time], verbose_name='Encounter Date and Time')),
                ('provider_satisfaction', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Provider Satisfaction')),
                ('patient_satisfaction', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Patient Satisfaction')),
                ('type', models.CharField(choices=[('clinic', 'Clinic'), ('simcenter', 'Sim Center'), ('pennpersonalizedcare', 'Penn Personalized Care')], default='clinic', max_length=20)),
                ('is_deidentified', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Is Deidentified')),
                ('is_restricted', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Is Restricted')),
                ('tier_id', models.IntegerField(default=5, help_text='References accounts.Tier.id (1-5, defaults to 5 for highest restriction)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.department')),
                ('encounter_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinical.encountersource', verbose_name='Source')),
                ('multi_modal_data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encounter', to='clinical.multimodaldata')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinical.patient')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinical.provider')),
            ],
            options={
                'verbose_name': 'Encounter',
                'verbose_name_plural': 'Encounters',
            },
        ),
        migrations.CreateModel(
            name='EncounterFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(blank=True, choices=[('video', 'Video'), ('audio', 'Audio'), ('image', 'Image'), ('document', 'Document'), ('transcript', 'Transcript')], max_length=50, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='clinical.encounter')),
            ],
        ),
        migrations.AddConstraint(
            model_name='encounterfile',
            constraint=models.UniqueConstraint(fields=('encounter', 'file_path'), name='unique_file_per_encounter'),
        ),
    ]
