# Generated by Django 5.2.6 on 2026-02-03 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encounter",
            name="tier_id",
            field=models.IntegerField(
                db_index=True,
                default=5,
                help_text="References accounts.Tier.id (1-5, defaults to 5 for highest restriction)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
