# Generated by Django 5.2.6 on 2026-02-10 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0002_alter_encounter_tier_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="encounter",
            name="tier_id",
        ),
        migrations.AddField(
            model_name="encounter",
            name="tier_level",
            field=models.IntegerField(
                db_index=True,
                default=5,
                help_text="Tier level (1-5) for data access control. Defaults to 5 for highest restriction.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
