# Generated by Django 5.2.6 on 2026-02-11 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0003_remove_encounter_tier_id_encounter_tier_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encounter",
            name="tier_level",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=5,
                help_text="Tier level (1-5) for data access control. Higher levels can access lower tier data.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
