# Generated by Django 5.2.6 on 2026-02-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0004_alter_encounter_tier_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encounterfile",
            name="file_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("image", "Image"),
                    ("document", "Document"),
                    ("transcript", "Transcript"),
                    ("room_view", "Room View"),
                    ("provider_view", "Provider View"),
                    ("patient_view", "Patient View"),
                    ("patient_survey", "Patient Survey"),
                    ("provider_survey", "Provider Survey"),
                    ("provider_annotation", "Provider Annotation"),
                    ("patient_annotation", "Patient Annotation"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
