"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
# from dashboard.utils import SanitizingHandler  # TODO: Move to shared app
import pymysql
from datetime import timedelta

pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS').split(',')

APPEND_SLASH = True

CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS').split(',')

# CORS Configuration - Environment specific allowed origins
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='http://localhost:3000,http://127.0.0.1:3000,http://localhost:8000,http://127.0.0.1:8000').split(',')

# Documentation URL
DOCUMENTATION_URL = config('DOCUMENTATION_URL')

# Basic Security Settings
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'clinical',
    'research',
    'shared',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist',
]

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'debug': DEBUG,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('ACCOUNTS_DB_NAME', default='observer_accounts'),
        'USER': config('ACCOUNTS_DB_USER', default=config('DB_USER')),
        'PASSWORD': config('ACCOUNTS_DB_PASSWORD', default=config('DB_PASSWORD')),
        'HOST': config('ACCOUNTS_DB_HOST', default=config('DB_HOST')),
        'PORT': config('ACCOUNTS_DB_PORT', default=config('DB_PORT')),
        'TEST': {
            'NAME': config('TEST_DEFAULT_DB', default='test_observer_default'),
            'DEPENDENCIES': [],
        },
    },
    'accounts': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('ACCOUNTS_DB_NAME', default='observer_accounts'),
        'USER': config('ACCOUNTS_DB_USER', default=config('DB_USER')),
        'PASSWORD': config('ACCOUNTS_DB_PASSWORD', default=config('DB_PASSWORD')),
        'HOST': config('ACCOUNTS_DB_HOST', default=config('DB_HOST')),
        'PORT': config('ACCOUNTS_DB_PORT', default=config('DB_PORT')),
        'TEST': {
            'NAME': config('TEST_ACCOUNTS_DB', default='test_observer_accounts'),
            'DEPENDENCIES': [],
        },
    },
    'clinical': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('CLINICAL_DB_NAME', default='observer_clinical'),
        'USER': config('CLINICAL_DB_USER', default=config('DB_USER')),
        'PASSWORD': config('CLINICAL_DB_PASSWORD', default=config('DB_PASSWORD')),
        'HOST': config('CLINICAL_DB_HOST', default=config('DB_HOST')),
        'PORT': config('CLINICAL_DB_PORT', default=config('DB_PORT')),
        'TEST': {
            'NAME': config('TEST_CLINICAL_DB', default='test_observer_clinical'),
            'DEPENDENCIES': ['accounts'],
        },
    },
    'research': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('RESEARCH_DB_NAME', default='observer_research'),
        'USER': config('RESEARCH_DB_USER', default=config('DB_USER')),
        'PASSWORD': config('RESEARCH_DB_PASSWORD', default=config('DB_PASSWORD')),
        'HOST': config('RESEARCH_DB_HOST', default=config('DB_HOST')),
        'PORT': config('RESEARCH_DB_PORT', default=config('DB_PORT')),
        'TEST': {
            'NAME': config('TEST_RESEARCH_DB', default='test_observer_research'),
            'DEPENDENCIES': [],
        },
    }
}

# Database routing
DATABASE_ROUTERS = ['shared.db_router.DatabaseRouter']


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {
            'user_attributes': ('username', 'first_name', 'last_name', 'email'),
            'max_similarity': 0.7,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,  # Enhanced from default 8
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Media files (user uploads, videos, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Azure Data Lake Storage settings
AZURE_STORAGE_ACCOUNT_NAME = config('AZURE_STORAGE_ACCOUNT_NAME')
AZURE_STORAGE_FILE_SYSTEM_NAME = config('AZURE_STORAGE_FILE_SYSTEM_NAME')
AZURE_SAS_TOKEN = config('AZURE_SAS_TOKEN')

# Logging settings
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, config('LOG_FILE')),
            'formatter': 'verbose',
        },
        # 'sanitizing': {
        #     'class': 'dashboard.utils.SanitizingHandler',
        #     'formatter': 'verbose',
        # },
    },
    'loggers': {
        '': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
    },
}


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),  # Increased from 10 minutes to 1 hour
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Increased from 1 day to 7 days
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

