# Generated by Django 5.0.1 on 2024-01-11 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=200, unique=True)),
                ('visit_type', models.CharField(choices=[('VATO', 'Video + Audio + Transcript + Annotations'), ('VAT', 'Video + Audio + Transcript'), ('VA', 'Video + Audio'), ('AT', 'Audio + Transcript'), ('VT', 'Video + Transcript'), ('VO', 'Video + Annotations'), ('AO', 'Audio + Annotations'), ('TO', 'Transcript + Annotations'), ('VAT', 'Video + Audio + Transcript'), ('VAO', 'Video + Audio + Annotations'), ('VTO', 'Video + Transcript + Annotations'), ('ATO', 'Audio + Transcript + Annotations'), ('V', 'Video Only'), ('A', 'Audio Only'), ('T', 'Transcript Only'), ('O', 'Annotations Only'), ('OTH', 'Others')], default='VAT', max_length=10)),
                ('is_deidentified', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('is_restricted', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('visit_date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.department')),
            ],
        ),
    ]
