# Generated by Django 5.0.1 on 2024-04-17 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='patient_satisfaction',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Patient Satisfaction'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='provider_satisfaction',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Provider Satisfaction'),
        ),
    ]
