# Generated by Django 5.0.1 on 2024-01-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='other_files',
            field=models.FileField(blank=True, null=True, upload_to='other_files/'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='transcript',
            field=models.FileField(blank=True, null=True, upload_to='transcript/'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
