# Generated by Django 5.0.1 on 2024-01-11 19:25

from django.db import migrations

DEPARTMENTS_NAMES = [
    'sim-center',
    'oncology',
    'primary-care',
    'neurology',
    'fmaily-medicine',
]

def populate_departments(apps, schema_editor):
    Departments = apps.get_model('dashboard', 'Department')
    for name in DEPARTMENTS_NAMES:
        Departments.objects.create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_departments),
    ]
