# Generated by Django 5.0.1 on 2024-01-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20240111_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='age_range',
            field=models.CharField(choices=[('18-20', '18-20'), ('21-30', '21-30'), ('31-40', '31-40'), ('41-50', '41-50'), ('51-60', '51-60'), ('61-70', '61-70'), ('71-80', '71-80'), ('81+', '81+')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='ethnic_category',
            field=models.CharField(choices=[('H', 'Hispanic or Latino'), ('NH', 'Not Hispanic or Latino'), ('UN', 'Unknown or Not Reported Ethnicity')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('UN', 'Unknown or Not Reported')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='racial_category',
            field=models.CharField(choices=[('AI', 'American Indian or Alaska Native'), ('A', 'Asian'), ('NHPI', 'Native Hawaiian or Other Pacific Islander'), ('B', 'Black or African American'), ('W', 'White'), ('M', 'More than One Race'), ('UN', 'Unknown or Not Reported')], max_length=4, null=True),
        ),
    ]
