# Generated by Django 5.0.1 on 2024-07-08 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_add_csn_number_to_encounter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encounter",
            name="csn_number",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]*$", "Only numeric characters are allowed."
                    )
                ],
                verbose_name="CSN Number",
            ),
        ),
    ]
