# Generated by Django 5.0.1 on 2024-04-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_encounter_case_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='case_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
