# Generated by Django 5.0.1 on 2024-01-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_encounter_age_range_encounter_ethnic_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Video', 'Video'), ('Audio', 'Audio'), ('Transcript', 'Transcript'), ('Annotation', 'Annotation')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='visit_type',
        ),
        migrations.AddField(
            model_name='encounter',
            name='media_types',
            field=models.ManyToManyField(to='dashboard.choice'),
        ),
    ]
