# Generated by Django 5.0.1 on 2024-08-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_encounter_csn_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='csn_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='CSN Number'),
        ),
    ]
