# Generated by Django 5.0.1 on 2024-08-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_encounter_csn_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimodaldatapath',
            name='patient_annotation',
            field=models.URLField(blank=True, null=True, verbose_name='Patient Annotation'),
        ),
        migrations.AddField(
            model_name='multimodaldatapath',
            name='provider_annotation',
            field=models.URLField(blank=True, null=True, verbose_name='Provider Annotation'),
        ),
    ]
