# Generated by Django 5.0.1 on 2024-01-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_choice_remove_encounter_visit_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='age_range',
            field=models.CharField(choices=[('18-20', '18-20'), ('21-30', '21-30'), ('31-40', '31-40'), ('41-50', '41-50'), ('51-60', '51-60'), ('61-70', '61-70'), ('71-80', '71-80'), ('81+', '81+'), ('UN', 'Unknown or Not Reported')], max_length=5, null=True),
        ),
    ]
