# Generated by Django 5.0.1 on 2024-04-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_encounter_case_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimodaldatapath',
            name='multi_modal_data_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Multi Modal Data ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='provider',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
