# Generated by Django 5.0.1 on 2024-03-11 19:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_alter_encounter_age_range"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultiModalDataPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_view", models.CharField(max_length=255)),
                ("patient_view", models.CharField(max_length=255)),
                ("room_view", models.CharField(max_length=255)),
                ("audio", models.CharField(max_length=255)),
                ("transcript", models.CharField(max_length=255)),
                ("patient_survey_path", models.CharField(max_length=255)),
                ("provider_survey_path", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.CharField(max_length=200, unique=True)),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("date_of_birth", models.DateField()),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("UN", "Unknown or Not Reported"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "race",
                    models.CharField(
                        choices=[
                            ("AI", "American Indian or Alaska Native"),
                            ("A", "Asian"),
                            ("NHPI", "Native Hawaiian or Other Pacific Islander"),
                            ("B", "Black or African American"),
                            ("W", "White"),
                            ("M", "More than One Race"),
                            ("UN", "Unknown or Not Reported"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "ethnicity",
                    models.CharField(
                        choices=[
                            ("H", "Hispanic or Latino"),
                            ("NH", "Not Hispanic or Latino"),
                            ("UN", "Unknown or Not Reported Ethnicity"),
                        ],
                        max_length=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_id", models.CharField(max_length=200, unique=True)),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("date_of_birth", models.DateField()),
                ("sex", models.CharField(max_length=200)),
                ("race", models.CharField(max_length=200)),
                ("ethnicity", models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name="encounter",
            name="media_types",
        ),
        migrations.RemoveField(
            model_name="encounter",
            name="age_range",
        ),
        migrations.RemoveField(
            model_name="encounter",
            name="ethnic_category",
        ),
        migrations.RemoveField(
            model_name="encounter",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="encounter",
            name="racial_category",
        ),
        migrations.RemoveField(
            model_name="encounter",
            name="visit_date",
        ),
        migrations.AddField(
            model_name="encounter",
            name="encounter_date",
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="encounter",
            name="encounter_time",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="encounter",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.department",
            ),
        ),
        migrations.AlterField(
            model_name="encounter",
            name="is_deidentified",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="encounter",
            name="is_restricted",
            field=models.BooleanField(),
        ),
        migrations.CreateModel(
            name="AnonymizedMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anonymized_encounter_id",
                    models.CharField(max_length=255, unique=True),
                ),
                ("anonymized_patient_id", models.CharField(max_length=255)),
                ("anonymized_provider_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "encounter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.encounter",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="encounter",
            name="multi_modal_data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.multimodaldatapath",
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.patient",
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.provider",
            ),
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
    ]
