# Generated by Django 5.0.1 on 2024-08-12 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_multimodaldatapath_patient_annotation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='patient_satisfaction',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Patient Satisfaction'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='provider_satisfaction',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Provider Satisfaction'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
