# Generated by Django 5.0.1 on 2024-03-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_multimodaldatapath_patient_provider_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="ethnicity",
            field=models.CharField(
                choices=[
                    ("H", "Hispanic or Latino"),
                    ("NH", "Not Hispanic or Latino"),
                    ("UN", "Unknown or Not Reported Ethnicity"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="race",
            field=models.CharField(
                choices=[
                    ("AI", "American Indian or Alaska Native"),
                    ("A", "Asian"),
                    ("NHPI", "Native Hawaiian or Other Pacific Islander"),
                    ("B", "Black or African American"),
                    ("W", "White"),
                    ("M", "More than One Race"),
                    ("UN", "Unknown or Not Reported"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="sex",
            field=models.CharField(
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("UN", "Unknown or Not Reported"),
                ],
                max_length=5,
            ),
        ),
    ]
