# Generated by Django 5.0.1 on 2024-08-27 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_encounter_patient_satisfaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='multi_modal_data',
        ),
        migrations.RemoveField(
            model_name='encounterrias',
            name='multi_modal_data',
        ),
        migrations.RemoveField(
            model_name='encountersimcenter',
            name='multi_modal_data',
        ),
        migrations.CreateModel(
            name='EncounterFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dashboard.encounter')),
            ],
        ),
    ]
