# Generated by Django 5.0.1 on 2024-10-02 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_encounter_multi_modal_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounterfile',
            name='encounter_rias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dashboard.encounterrias'),
        ),
        migrations.AddField(
            model_name='encounterfile',
            name='encounter_sim_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dashboard.encountersimcenter'),
        ),
        migrations.AlterField(
            model_name='encounterfile',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dashboard.encounter'),
        ),
        migrations.AlterField(
            model_name='encounterfile',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='encounterfile',
            name='file_type',
            field=models.CharField(blank=True, choices=[('room_view', 'Room View'), ('provider_view', 'Provider View'), ('patient_view', 'Patient View'), ('audio', 'Audio'), ('transcript', 'Transcript'), ('patient_survey', 'Patient Survey'), ('provider_survey', 'Provider Survey'), ('patient_annotation', 'Patient Annotation'), ('provider_annotation', 'Provider Annotation'), ('rias_transcript', 'RIAS Transcript'), ('rias_codes', 'RIAS Codes'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
