# Generated by Django 5.0.1 on 2024-03-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0008_alter_multimodaldatapath_audio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multimodaldatapath",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="audios/"),
        ),
        migrations.AlterField(
            model_name="multimodaldatapath",
            name="patient_survey_path",
            field=models.FileField(blank=True, null=True, upload_to="patient_surveys/"),
        ),
        migrations.AlterField(
            model_name="multimodaldatapath",
            name="patient_view",
            field=models.FileField(blank=True, null=True, upload_to="patient_views/"),
        ),
        migrations.AlterField(
            model_name="multimodaldatapath",
            name="provider_survey_path",
            field=models.FileField(
                blank=True, null=True, upload_to="provider_surveys/"
            ),
        ),
        migrations.AlterField(
            model_name="multimodaldatapath",
            name="provider_view",
            field=models.FileField(blank=True, null=True, upload_to="provider_views/"),
        ),
        migrations.AlterField(
            model_name="multimodaldatapath",
            name="room_view",
            field=models.FileField(blank=True, null=True, upload_to="room_views/"),
        ),
        migrations.AlterField(
            model_name="multimodaldatapath",
            name="transcript",
            field=models.FileField(blank=True, null=True, upload_to="transcripts/"),
        ),
    ]
