# Generated by Django 5.0.1 on 2024-11-07 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_encounterfile_encounter_rias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='multi_modal_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encounter', to='dashboard.multimodaldatapath'),
        ),
        migrations.AddField(
            model_name='encounterfile',
            name='encounter_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.encountersource'),
        ),
        migrations.AddField(
            model_name='encounterfile',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='encounterrias',
            name='multi_modal_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encounter_rias', to='dashboard.multimodaldatapath'),
        ),
        migrations.AddField(
            model_name='encountersimcenter',
            name='multi_modal_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encounter_sim_center', to='dashboard.multimodaldatapath'),
        ),
        migrations.AlterField(
            model_name='multimodaldatapath',
            name='audio',
            field=models.BooleanField(default=False, verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='multimodaldatapath',
            name='patient_annotation',
            field=models.BooleanField(default=False, verbose_name='Patient Annotation'),
        ),
        migrations.AlterField(
            model_name='multimodaldatapath',
            name='patient_survey',
            field=models.BooleanField(default=False, verbose_name='Patient Survey'),
        ),
        migrations.AlterField(
            model_name='multimodaldatapath',
            name='patient_view',
            field=models.BooleanField(default=False, verbose_name='Patient View'),
        ),
        migrations.AlterField(
            model_name='multimodaldatapath',
            name='provider_annotation',
            field=models.BooleanField(default=False, verbose_name='Provider Annotation'),
        ),
        migrations.AlterField(
            model_name='multimodaldatapath',
            name='provider_survey',
            field=models.BooleanField(default=False, verbose_name='Provider Survey'),
        ),
        migrations.AlterField(
            model_name='multimodaldatapath',
            name='provider_view',
            field=models.BooleanField(default=False, verbose_name='Provider View'),
        ),
        migrations.AlterField(
            model_name='multimodaldatapath',
            name='rias_codes',
            field=models.BooleanField(default=False, verbose_name='RIAS Codes'),
        ),
        migrations.AlterField(
            model_name='multimodaldatapath',
            name='rias_transcript',
            field=models.BooleanField(default=False, verbose_name='RIAS Transcript'),
        ),
        migrations.AlterField(
            model_name='multimodaldatapath',
            name='room_view',
            field=models.BooleanField(default=False, verbose_name='Room View'),
        ),
        migrations.AlterField(
            model_name='multimodaldatapath',
            name='transcript',
            field=models.BooleanField(default=False, verbose_name='Transcript'),
        ),
    ]
