# Generated by Django 5.0.1 on 2024-03-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0009_alter_multimodaldatapath_audio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="multimodaldatapath",
            name="multi_modal_data_id",
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="multimodaldatapath",
            name="audio",
            field=models.FileField(
                blank=True, null=True, upload_to="media/encouter/audios/"
            ),
        ),
        migrations.AlterField(
            model_name="multimodaldatapath",
            name="patient_survey_path",
            field=models.FileField(
                blank=True, null=True, upload_to="media/encouter/patient_surveys/"
            ),
        ),
        migrations.AlterField(
            model_name="multimodaldatapath",
            name="patient_view",
            field=models.FileField(
                blank=True, null=True, upload_to="media/encouter/patient_views/"
            ),
        ),
        migrations.AlterField(
            model_name="multimodaldatapath",
            name="provider_survey_path",
            field=models.FileField(
                blank=True, null=True, upload_to="media/encouter/provider_surveys/"
            ),
        ),
        migrations.AlterField(
            model_name="multimodaldatapath",
            name="provider_view",
            field=models.FileField(
                blank=True, null=True, upload_to="media/encouter/provider_views/"
            ),
        ),
        migrations.AlterField(
            model_name="multimodaldatapath",
            name="room_view",
            field=models.FileField(
                blank=True, null=True, upload_to="media/encouter/room_views/"
            ),
        ),
        migrations.AlterField(
            model_name="multimodaldatapath",
            name="transcript",
            field=models.FileField(
                blank=True, null=True, upload_to="media/encouter/transcripts/"
            ),
        ),
    ]
