# Generated by Django 5.0.1 on 2024-03-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0010_multimodaldatapath_multi_modal_data_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encounter",
            name="is_deidentified",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], default=True
            ),
        ),
        migrations.AlterField(
            model_name="encounter",
            name="is_restricted",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], default=True
            ),
        ),
    ]
