# Generated by Django 5.0.1 on 2024-03-13 02:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0011_alter_encounter_is_deidentified_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnonymizedMapping",
        ),
    ]
