# Generated by Django 5.0.1 on 2024-11-12 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_alter_profile_date_of_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="encounterfile",
            name="encounter_rias",
        ),
        migrations.RemoveField(
            model_name="encountersimcenter",
            name="department",
        ),
        migrations.RemoveField(
            model_name="encountersimcenter",
            name="encounter_source",
        ),
        migrations.RemoveField(
            model_name="encountersimcenter",
            name="multi_modal_data",
        ),
        migrations.RemoveField(
            model_name="encountersimcenter",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="encountersimcenter",
            name="provider",
        ),
        migrations.RemoveField(
            model_name="encounterfile",
            name="encounter_sim_center",
        ),
        migrations.AlterModelOptions(
            name="encounter",
            options={"verbose_name": "Encounter", "verbose_name_plural": "Encounters"},
        ),
        migrations.AddField(
            model_name="encounter",
            name="case_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Case ID"
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="type",
            field=models.CharField(
                choices=[
                    ("clinic", "Clinic"),
                    ("simcenter", "Sim Center"),
                    ("rias", "RIAS"),
                ],
                default="clinic",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="providers",
                to="dashboard.department",
            ),
        ),
        migrations.AlterField(
            model_name="encounter",
            name="csn_number",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="CSN Number",
            ),
        ),
        migrations.DeleteModel(
            name="EncounterRIAS",
        ),
        migrations.DeleteModel(
            name="EncounterSimCenter",
        ),
    ]
