# Generated by Django 5.0.1 on 2024-11-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_remove_encounterfile_encounter_rias_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MultiModalDataPath",
            new_name="MultiModalData",
        ),
    ]
