# Generated by Django 5.0.1 on 2024-03-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0012_delete_anonymizedmapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encounter",
            name="is_deidentified",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], default=False
            ),
        ),
    ]
