# Generated by Django 5.0.1 on 2024-03-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0013_alter_encounter_is_deidentified"),
    ]

    operations = [
        migrations.AddField(
            model_name="encounter",
            name="overall_satisfaction",
            field=models.IntegerField(default=0),
        ),
    ]
