# Generated by Django 5.0.1 on 2024-11-19 01:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_rename_multimodaldatapath_multimodaldata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("website", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tier_name", models.CharField(max_length=10)),
                ("complete_deidentification", models.BooleanField(default=False)),
                (
                    "blur_sexually_explicit_body_parts",
                    models.BooleanField(default=False),
                ),
                ("blur_face", models.BooleanField(default=False)),
                ("obscure_voice", models.BooleanField(default=False)),
                ("dua", models.BooleanField(default=False)),
                ("external_access", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="encounterfile",
            name="encounter_source",
        ),
        migrations.RemoveField(
            model_name="provider",
            name="department",
        ),
        migrations.AlterField(
            model_name="encounter",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.patient",
            ),
        ),
        migrations.AlterField(
            model_name="encounter",
            name="patient_satisfaction",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[django.core.validators.MaxValueValidator(5)],
                verbose_name="Patient Satisfaction",
            ),
        ),
        migrations.AlterField(
            model_name="encounter",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.provider",
            ),
        ),
        migrations.AlterField(
            model_name="encounter",
            name="provider_satisfaction",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[django.core.validators.MaxValueValidator(5)],
                verbose_name="Provider Satisfaction",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.organization",
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="encounters",
                to="dashboard.tier",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.tier",
            ),
        ),
    ]
