# Generated by Django 5.0.1 on 2024-03-14 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0014_encounter_overall_satisfaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="encounter",
            name="multi_modal_data",
        ),
        migrations.AddField(
            model_name="multimodaldatapath",
            name="encounter",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="multi_modal_data",
                to="dashboard.encounter",
            ),
        ),
    ]
