# Generated by Django 5.0.1 on 2024-11-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_organization_tier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tier",
            name="level",
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
