# Generated by Django 5.0.1 on 2025-03-03 18:00

import dashboard.models.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_tier_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='case_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Case ID'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='patient_satisfaction',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Patient Satisfaction'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='provider_satisfaction',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Provider Satisfaction'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[dashboard.models.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[dashboard.models.validators.validate_zip_code]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[dashboard.models.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[dashboard.models.validators.validate_zip_code]),
        ),
        migrations.RemoveField(
            model_name="organization",
            name="address",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="address",
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=255, blank=True, null=True, verbose_name="Bio"),
        ),
        migrations.AddField(
            model_name='organization',
            name='address_1',
            field=models.CharField(max_length=100, blank=True, null=True, verbose_name="Address 1"),
        ),
        migrations.AddField(
            model_name='organization',
            name='address_2',
            field=models.CharField(max_length=100, blank=True, null=True, verbose_name="Address 2"),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_1',
            field=models.CharField(max_length=100, blank=True, null=True, verbose_name="Address 1"),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_2',
            field=models.CharField(max_length=100, blank=True, null=True, verbose_name="Address 2"),
        )
    ]
