# Generated by Django 5.0.1 on 2025-03-05 15:21

import dashboard.models.validators
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_tier_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='organization',
            name='address_1',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[dashboard.models.validators.validate_address]),
        ),
        migrations.AddField(
            model_name='organization',
            name='address_2',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[dashboard.models.validators.validate_address]),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_1',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[dashboard.models.validators.validate_address]),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_2',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[dashboard.models.validators.validate_address]),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[dashboard.models.validators.validate_field]),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='case_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Case ID'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='csn_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[dashboard.models.validators.validate_numeric], verbose_name='CSN Number'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='encounter_date_and_time',
            field=models.DateTimeField(default=datetime.datetime.now, validators=[dashboard.models.validators.validate_time], verbose_name='Encounter Date and Time'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='patient_satisfaction',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Patient Satisfaction'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='provider_satisfaction',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Provider Satisfaction'),
        ),
        migrations.AlterField(
            model_name='encountersource',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[dashboard.models.validators.validate_field]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[dashboard.models.validators.validate_field]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[dashboard.models.validators.validate_field]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100, validators=[dashboard.models.validators.validate_field]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[dashboard.models.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[dashboard.models.validators.validate_field]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, null=True, validators=[dashboard.models.validators.validate_website]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[dashboard.models.validators.validate_numeric]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[dashboard.models.validators.validate_time]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, validators=[dashboard.models.validators.validate_field]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, validators=[dashboard.models.validators.validate_field]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[dashboard.models.validators.validate_field]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[dashboard.models.validators.validate_field]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[dashboard.models.validators.validate_field]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[dashboard.models.validators.validate_time]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[dashboard.models.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[dashboard.models.validators.validate_field]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[dashboard.models.validators.validate_numeric]),
        ),
        migrations.AlterField(
            model_name='provider',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[dashboard.models.validators.validate_time]),
        ),
        migrations.AlterField(
            model_name='provider',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, validators=[dashboard.models.validators.validate_field]),
        ),
        migrations.AlterField(
            model_name='provider',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, validators=[dashboard.models.validators.validate_field]),
        ),
        migrations.AlterField(
            model_name='tier',
            name='level',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='tier',
            name='tier_name',
            field=models.CharField(max_length=10, validators=[dashboard.models.validators.validate_field]),
        ),
    ]
