# Generated by Django 5.0.1 on 2024-03-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0015_remove_encounter_multi_modal_data_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="encounter",
            old_name="overall_satisfaction",
            new_name="patient_satisfaction",
        ),
        migrations.AddField(
            model_name="encounter",
            name="provider_satisfaction",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="multimodaldatapath",
            name="audio",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="multimodaldatapath",
            name="patient_survey_path",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="multimodaldatapath",
            name="patient_view",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="multimodaldatapath",
            name="provider_survey_path",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="multimodaldatapath",
            name="provider_view",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="multimodaldatapath",
            name="room_view",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="multimodaldatapath",
            name="transcript",
            field=models.URLField(blank=True, null=True),
        ),
    ]
