# Generated by Django 5.0.1 on 2024-03-14 19:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "dashboard",
            "0016_rename_overall_satisfaction_encounter_patient_satisfaction_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="encounter",
            old_name="encounter_time",
            new_name="encounter_date_and_time",
        ),
        migrations.RemoveField(
            model_name="encounter",
            name="encounter_date",
        ),
    ]
