# Generated by Django 5.0.1 on 2024-03-15 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_rename_encounter_time_encounter_encounter_date_and_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='timestamp',
        ),
    ]
