# Generated by Django 5.0.1 on 2024-03-15 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_remove_encounter_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimodaldatapath',
            name='encounter',
        ),
        migrations.AddField(
            model_name='encounter',
            name='multi_modal_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.multimodaldatapath'),
        ),
    ]
