# Generated by Django 5.0.1 on 2024-03-15 02:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_remove_multimodaldatapath_encounter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='multimodaldatapath',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='patient',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='provider',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
