# Generated by Django 5.0.1 on 2024-03-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_encounter_timestamp_multimodaldatapath_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='multimodaldatapath',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
