# Generated by Django 5.0.1 on 2024-03-15 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_encounter_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='department',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='dashboard.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='encounter',
            name='patient',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dashboard.patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='encounter',
            name='provider',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dashboard.provider'),
            preserve_default=False,
        ),
    ]
