# Generated by Django 5.0.1 on 2024-03-15 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_encounter_department_alter_encounter_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multimodaldatapath',
            old_name='patient_survey_path',
            new_name='patient_survey',
        ),
        migrations.RenameField(
            model_name='multimodaldatapath',
            old_name='provider_survey_path',
            new_name='provider_survey',
        ),
    ]
