# Generated by Django 5.0.1 on 2024-03-27 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "dashboard",
            "0023_rename_patient_survey_path_multimodaldatapath_patient_survey_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="multimodaldatapath",
            name="rias_codes",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="multimodaldatapath",
            name="rias_transcript",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="RIAS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rias_case_id", models.CharField(max_length=200, unique=True)),
                (
                    "is_deidentified",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")], default=False
                    ),
                ),
                (
                    "is_restricted",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")], default=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "multi_modal_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.multimodaldatapath",
                    ),
                ),
            ],
        ),
    ]
