# Generated by Django 5.0.1 on 2025-08-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_agreementtype_agreement_useragreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Indicates whether the user has verified their email address'),
        ),
    ]
