# Generated by Django 5.2.6 on 2025-10-24 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_email_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, verbose_name="Cohort ID"),
                ),
                (
                    "name",
                    models.CharField(help_text="User-friendly name for the cohort", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description of the cohort's purpose",
                    ),
                ),
                ("filters", models.JSONField(help_text="VisitSearchFilters structure as JSON")),
                (
                    "visit_count",
                    models.IntegerField(
                        help_text="Number of visits matching filters at creation time"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who created this cohort",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohorts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cohort",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="cohort_user_id_c6521b_idx"),
                    models.Index(fields=["name"], name="cohort_name_c263f8_idx"),
                ],
            },
        ),
    ]
