# Generated by Django 5.2.6 on 2025-12-11 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_create_cohort_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditTrail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the action was performed"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Specific event type (e.g., EXPORT_SINGLE_TABLE, VIEW_PATIENT_RECORD)",
                        max_length=100,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DATA_EXPORT", "Data Export"),
                            ("DATA_VIEW", "Data View"),
                            ("DATA_SEARCH", "Data Search"),
                            ("AUTHENTICATION", "Authentication"),
                            ("CONFIGURATION", "Configuration"),
                            ("COHORT_MANAGEMENT", "Cohort Management"),
                        ],
                        help_text="High-level category of the event",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Human-readable description of the action"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Event-specific data (table names, record counts, etc.)",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Client IP address", null=True
                    ),
                ),
                ("user_agent", models.TextField(blank=True, help_text="Client user agent string")),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who performed the action",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_trail",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Trail Entry",
                "verbose_name_plural": "Audit Trail Entries",
                "db_table": "audit_trail",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["-timestamp"], name="audit_trail_timesta_c3dcfb_idx"),
                    models.Index(
                        fields=["user", "-timestamp"], name="audit_trail_user_id_fc5d0c_idx"
                    ),
                    models.Index(
                        fields=["category", "-timestamp"], name="audit_trail_categor_157001_idx"
                    ),
                    models.Index(fields=["event_type"], name="audit_trail_event_t_709100_idx"),
                ],
            },
        ),
    ]
