# Generated by Django 5.2.6 on 2025-12-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_passwordresettoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audittrail",
            name="category",
            field=models.CharField(
                choices=[
                    ("DATA_EXPORT", "Data Export"),
                    ("DATA_VIEW", "Data View"),
                    ("DATA_SEARCH", "Data Search"),
                    ("AUTHENTICATION", "Authentication"),
                    ("CONFIGURATION", "Configuration"),
                    ("COHORT_MANAGEMENT", "Cohort Management"),
                    ("PROFILE", "Profile"),
                ],
                help_text="High-level category of the event",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(fields=["user", "is_used"], name="pwd_reset_user_used_idx"),
        ),
    ]
