# Generated by Django 5.2.6 on 2026-02-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_audittrail_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="audittrail",
            name="user_identifier",
            field=models.CharField(
                blank=True,
                help_text="Snapshot of user email at time of action (preserved if user is deleted)",
                max_length=255,
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(fields=["user_identifier"], name="audit_trail_user_id_000948_idx"),
        ),
    ]
