# Generated by Django 5.2.6 on 2026-03-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_audittrail_user_identifier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohort",
            name="encounter_ids",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Optional list of encounter ID strings. When set, overrides filter-based lookup.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cohort",
            name="search_query",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Free-text search query (only used when source='search')",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="cohort",
            name="source",
            field=models.CharField(
                choices=[("research", "Research Tab"), ("search", "Encounter Search")],
                default="research",
                help_text="Origin of the cohort: 'research' for nested filters, 'search' for flat ES filters",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cohort",
            name="filters",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Filter criteria as JSON (format depends on source field)",
            ),
        ),
        migrations.AddIndex(
            model_name="cohort",
            index=models.Index(fields=["source"], name="cohort_source_02079e_idx"),
        ),
    ]
