# Generated by Django 5.0.1 on 2025-09-08 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Audit Log ID')),
                ('access_time', models.DateTimeField()),
                ('user_id', models.CharField(max_length=255)),
                ('workstation_id', models.CharField(max_length=255)),
                ('access_action', models.CharField(max_length=255)),
                ('metric_id', models.IntegerField(blank=True, null=True)),
                ('metric_name', models.CharField(max_length=255)),
                ('metric_desc', models.CharField(max_length=255)),
                ('metric_type', models.CharField(max_length=255)),
                ('metric_group', models.CharField(max_length=255)),
                ('event_action_type', models.CharField(max_length=255)),
                ('event_action_subtype', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('concept_id', models.IntegerField(primary_key=True, serialize=False)),
                ('concept_name', models.CharField(max_length=255)),
                ('domain_name', models.CharField(max_length=255)),
                ('vocabulary_name', models.CharField(max_length=255)),
                ('concept_class_name', models.CharField(max_length=255)),
                ('standard_concept', models.CharField(blank=True, max_length=255, null=True)),
                ('concept_code', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'concept',
            },
        ),
        migrations.CreateModel(
            name='ConditionOccurrence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Condition Occurrence ID')),
                ('is_primary_dx', models.CharField(max_length=255)),
                ('condition_source_value', models.CharField(max_length=255)),
                ('condition_concept_id', models.IntegerField()),
                ('concept_code', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'condition_occurrence',
            },
        ),
        migrations.CreateModel(
            name='DrugExposure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Drug Exposure ID')),
                ('drug_ordering_date', models.DateField(blank=True, null=True)),
                ('drug_exposure_start_datetime', models.DateTimeField(blank=True, null=True)),
                ('drug_exposure_end_datetime', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'drug_exposure',
            },
        ),
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Labs ID')),
                ('ordering_date_shifted', models.DateTimeField(blank=True, null=True)),
                ('procedure_id', models.IntegerField()),
                ('procedure_name', models.CharField(max_length=255)),
                ('procedure_code', models.CharField(max_length=255)),
                ('order_type', models.CharField(max_length=255)),
                ('order_status', models.CharField(max_length=255)),
                ('order_proc_deid', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('comp_result_name', models.CharField(max_length=255)),
                ('ord_value', models.CharField(blank=True, max_length=255, null=True)),
                ('ord_num_value', models.FloatField(blank=True, null=True)),
                ('reference_low', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_high', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('result_flag', models.CharField(blank=True, max_length=255, null=True)),
                ('lab_status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Labs',
                'db_table': 'labs',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Measurement ID')),
                ('bp_systolic', models.IntegerField(blank=True, null=True)),
                ('bp_diastolic', models.IntegerField(blank=True, null=True)),
                ('phys_bp', models.CharField(blank=True, max_length=255, null=True)),
                ('weight_lb', models.FloatField(blank=True, null=True)),
                ('height', models.CharField(blank=True, max_length=255, null=True)),
                ('pulse', models.IntegerField(blank=True, null=True)),
                ('phys_spo2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'measurement',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Note ID')),
                ('note_date', models.DateField()),
                ('note_text', models.TextField()),
                ('note_type', models.CharField(max_length=255)),
                ('note_status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'note',
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Observation ID')),
                ('file_type', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('observation_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'observation',
            },
        ),
        migrations.CreateModel(
            name='PatientSurvey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Patient Survey ID')),
                ('form_1_timestamp', models.DateTimeField(null=True)),
                ('visit_date', models.DateField(null=True)),
                ('patient_overall_health', models.FloatField(blank=True, null=True)),
                ('patient_mental_emotional_health', models.FloatField(blank=True, null=True)),
                ('patient_age', models.FloatField(blank=True, null=True)),
                ('patient_education', models.FloatField(blank=True, null=True)),
                ('overall_satisfaction_scale_1', models.FloatField(blank=True, null=True)),
                ('overall_satisfaction_scale_2', models.FloatField(blank=True, null=True)),
                ('tech_experience_1', models.FloatField(blank=True, null=True)),
                ('tech_experience_2', models.FloatField(blank=True, null=True)),
                ('relationship_with_provider_1', models.FloatField(blank=True, null=True)),
                ('relationship_with_provider_2', models.FloatField(blank=True, null=True)),
                ('hawthorne_1', models.FloatField(blank=True, null=True)),
                ('hawthorne_2', models.FloatField(blank=True, null=True)),
                ('hawthorne_3', models.FloatField(blank=True, null=True)),
                ('hawthorne_4', models.FloatField(blank=True, null=True)),
                ('visit_related_1', models.FloatField(blank=True, null=True)),
                ('visit_related_2', models.FloatField(blank=True, null=True)),
                ('visit_related_3', models.FloatField(blank=True, null=True)),
                ('visit_related_4', models.FloatField(blank=True, null=True)),
                ('visit_related_5', models.FloatField(blank=True, null=True)),
                ('visit_related_6', models.FloatField(blank=True, null=True)),
                ('hawthorne_5', models.FloatField(blank=True, null=True)),
                ('open_ended_interaction', models.TextField(blank=True, null=True)),
                ('open_ended_change', models.TextField(blank=True, null=True)),
                ('open_ended_experience', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patient_survey',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Person ID')),
                ('year_of_birth', models.IntegerField(null=True)),
                ('gender_source_value', models.CharField(blank=True, max_length=255, null=True)),
                ('gender_source_concept_id', models.IntegerField(blank=True, null=True)),
                ('race_source_value', models.CharField(blank=True, max_length=255, null=True)),
                ('race_source_concept_id', models.IntegerField(blank=True, null=True)),
                ('ethnicity_source_value', models.CharField(max_length=255, null=True)),
                ('ethnicity_source_concept_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='ProcedureOccurrence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Procedure Occurrence ID')),
                ('procedure_ordering_date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('future_or_stand', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'procedure_occurrence',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Provider ID')),
                ('year_of_birth', models.IntegerField(null=True)),
                ('gender_source_value', models.CharField(blank=True, max_length=255, null=True)),
                ('gender_source_concept_id', models.IntegerField(blank=True, null=True)),
                ('race_source_value', models.CharField(blank=True, max_length=255, null=True)),
                ('race_source_concept_id', models.IntegerField(blank=True, null=True)),
                ('ethnicity_source_value', models.CharField(max_length=255, null=True)),
                ('ethnicity_source_concept_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'provider',
            },
        ),
        migrations.CreateModel(
            name='ProviderSurvey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Provider Survey ID')),
                ('form_1_timestamp', models.DateTimeField(null=True)),
                ('visit_date', models.DateField(null=True)),
                ('years_hcp_experience', models.IntegerField(blank=True, null=True)),
                ('tech_experience', models.IntegerField(blank=True, null=True)),
                ('communication_method_1', models.IntegerField(blank=True, null=True)),
                ('communication_method_2', models.IntegerField(blank=True, null=True)),
                ('communication_method_3', models.IntegerField(blank=True, null=True)),
                ('communication_method_4', models.IntegerField(blank=True, null=True)),
                ('communication_method_5', models.IntegerField(blank=True, null=True)),
                ('communication_other', models.CharField(blank=True, max_length=255, null=True)),
                ('inbasket_messages', models.IntegerField(blank=True, null=True)),
                ('overall_satisfaction_scale_1', models.IntegerField(blank=True, null=True)),
                ('overall_satisfaction_scale_2', models.IntegerField(blank=True, null=True)),
                ('patient_related_1', models.IntegerField(blank=True, null=True)),
                ('patient_related_2', models.IntegerField(blank=True, null=True)),
                ('patient_related_3', models.IntegerField(blank=True, null=True)),
                ('visit_related_1', models.IntegerField(blank=True, null=True)),
                ('visit_related_2', models.IntegerField(blank=True, null=True)),
                ('visit_related_4', models.IntegerField(blank=True, null=True)),
                ('hawthorne_1', models.IntegerField(blank=True, null=True)),
                ('hawthorne_2', models.IntegerField(blank=True, null=True)),
                ('hawthorne_3', models.IntegerField(blank=True, null=True)),
                ('open_ended_1', models.TextField(blank=True, null=True)),
                ('open_ended_2', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'provider_survey',
            },
        ),
        migrations.CreateModel(
            name='VisitOccurrence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Visit Occurrence ID')),
                ('visit_start_date', models.DateField(blank=True, null=True)),
                ('visit_start_time', models.TimeField(blank=True, null=True)),
                ('visit_source_value', models.CharField(max_length=255)),
                ('visit_source_id', models.IntegerField()),
                ('tier_id', models.IntegerField(help_text='Tier level for data access control')),
            ],
            options={
                'db_table': 'visit_occurrence',
            },
        ),
        migrations.AddConstraint(
            model_name='concept',
            constraint=models.UniqueConstraint(fields=('concept_code', 'vocabulary_name'), name='unique_concept_code_per_vocabulary'),
        ),
        migrations.AddField(
            model_name='note',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.person'),
        ),
        migrations.AddField(
            model_name='labs',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.person'),
        ),
        migrations.AddField(
            model_name='note',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.provider'),
        ),
        migrations.AddField(
            model_name='visitoccurrence',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.person'),
        ),
        migrations.AddField(
            model_name='visitoccurrence',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.provider'),
        ),
        migrations.AddField(
            model_name='providersurvey',
            name='visit_occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.visitoccurrence'),
        ),
        migrations.AddField(
            model_name='procedureoccurrence',
            name='visit_occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.visitoccurrence'),
        ),
        migrations.AddField(
            model_name='patientsurvey',
            name='visit_occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.visitoccurrence'),
        ),
        migrations.AddField(
            model_name='observation',
            name='visit_occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.visitoccurrence'),
        ),
        migrations.AddField(
            model_name='note',
            name='visit_occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.visitoccurrence'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='visit_occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.visitoccurrence'),
        ),
        migrations.AddField(
            model_name='drugexposure',
            name='visit_occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.visitoccurrence'),
        ),
        migrations.AddField(
            model_name='conditionoccurrence',
            name='visit_occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.visitoccurrence'),
        ),
        migrations.AddField(
            model_name='auditlogs',
            name='visit_occurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='research.visitoccurrence'),
        ),
    ]
