# Generated by Django 5.0.1 on 2025-09-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlogs',
            options={'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.AlterModelOptions(
            name='labs',
            options={'verbose_name_plural': 'Labs'},
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='access_action',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='access_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='event_action_subtype',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='event_action_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='metric_desc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='metric_group',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='metric_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='metric_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='workstation_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='concept',
            name='concept_class_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='concept',
            name='concept_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='concept',
            name='domain_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='concept',
            name='standard_concept',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conditionoccurrence',
            name='concept_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='conditionoccurrence',
            name='condition_source_value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='conditionoccurrence',
            name='is_primary_dx',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='drugexposure',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='drugexposure',
            name='drug_exposure_end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drugexposure',
            name='drug_exposure_start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drugexposure',
            name='drug_ordering_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drugexposure',
            name='quantity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='comp_result_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='labs',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='labs',
            name='lab_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='ord_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='order_proc_deid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='labs',
            name='order_status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='labs',
            name='order_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='labs',
            name='ordering_date_shifted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='procedure_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='labs',
            name='procedure_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='labs',
            name='reference_high',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='reference_low',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='reference_unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='result_flag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='height',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='phys_bp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='observation',
            name='file_path',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='observation',
            name='file_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientsurvey',
            name='form_1_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='patientsurvey',
            name='open_ended_change',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientsurvey',
            name='open_ended_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientsurvey',
            name='open_ended_interaction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientsurvey',
            name='visit_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='ethnicity_source_concept_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='ethnicity_source_value',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender_source_concept_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender_source_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='race_source_concept_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='race_source_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='year_of_birth',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='procedureoccurrence',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='procedureoccurrence',
            name='future_or_stand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='procedureoccurrence',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='provider',
            name='ethnicity_source_concept_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='ethnicity_source_value',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='gender_source_concept_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='gender_source_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='race_source_concept_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='race_source_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='year_of_birth',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='providersurvey',
            name='communication_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='providersurvey',
            name='form_1_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='providersurvey',
            name='open_ended_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='providersurvey',
            name='open_ended_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='providersurvey',
            name='visit_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='visitoccurrence',
            name='visit_source_value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='visitoccurrence',
            name='visit_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitoccurrence',
            name='visit_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
