# Generated by Django 5.2.6 on 2026-02-10 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitoccurrence",
            name="tier_id",
        ),
        migrations.AddField(
            model_name="visitoccurrence",
            name="tier_level",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=5,
                help_text="Tier level (1-5) for data access control. Higher levels can access lower tier data.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
